name: wb-mpc
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pinocchio=3.3.0
  - casadi=3.6.7
  - meshcat-python
  - matplotlib
  - scipy
  - pyyaml
  - osqp
  - pip
  - pip:
      - mujoco==3.1.6
